--------------------------------
-- MANAGER
--------------------------------
DROP TABLE Manager CASCADE CONSTRAINTS;

CREATE TABLE Manager (
	"MN_NO"	NUMBER		        NOT NULL,
	"MN_ID"	VARCHAR2(50)		NOT NULL,
	"MN_PWD"	VARCHAR2(50)	NOT NULL,
	"MN_NICK"	VARCHAR2(100)	NOT NULL
);


ALTER TABLE Manager ADD CONSTRAINT "PK_MANAGER" PRIMARY KEY (
	"MN_NO"
);


DROP SEQUENCE SEQ_Manager_NO;
CREATE SEQUENCE SEQ_Manager_NO NOCACHE NOCYCLE;

INSERT INTO Manager(MN_NO, MN_ID, MN_PWD, MN_NICK) VALUES (SEQ_MANAGER_NO.NEXTVAL, 'admin', '1234', '관리자');
COMMIT;
SELECT * FROM Manager;

--------------------------------
-- CATEGORY
--------------------------------
DROP TABLE M_CATEGORY CASCADE CONSTRAINTS;
CREATE TABLE M_CATEGORY(
    CATEGORY_NO     NUMBER           PRIMARY KEY,
    CATEGORY_NAME   VARCHAR2(30)     NOT NULL
);

INSERT INTO M_CATEGORY(CATEGORY_NO , CATEGORY_NAME) VALUES(10, '공지사항');
INSERT INTO M_CATEGORY(CATEGORY_NO , CATEGORY_NAME) VALUES(20, 'FAQ');
INSERT INTO M_CATEGORY(CATEGORY_NO , CATEGORY_NAME) VALUES(30, '사용자 제재');
COMMIT;

SELECT * FROM M_CATEGORY;



UPDATE Notice SET N_CNT = N_CNT+1 WHERE N_NO = 91 AND STATUS = 'N';



