--------------------------------
-- NOTICE
--------------------------------
DROP TABLE Notice CASCADE CONSTRAINTS;

CREATE TABLE Notice (
	"N_NO"	    NUMBER		                NOT NULL,
    "N_CATE"	VARCHAR2(100)		        NOT NULL,
	"N_TITLE"	VARCHAR2(100)		        NOT NULL,
	"N_CONTENT"	VARCHAR2(1000)		        NOT NULL,
	"N_CNT"	    NUMBER	    DEFAULT 0	    NOT NULL,
	"N_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"N_MOD"	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN Notice."N_CATE" IS '공지사항/FAQ';

ALTER TABLE Notice ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"N_NO"
);

DROP SEQUENCE SEQ_Notice_NO;
CREATE SEQUENCE SEQ_Notice_NO NOCACHE NOCYCLE;

INSERT INTO Notice(N_NO, N_CATE, N_TITLE, N_CONTENT) VALUES(SEQ_NOTICE_NO.NEXTVAL, '공지', '추석 인사', '한가위 잘 보내시길 바랍니다!');
COMMIT;
SELECT * FROM Notice;