--------------------------------
-- NOTICE
--------------------------------
DROP TABLE Notice CASCADE CONSTRAINTS;

CREATE TABLE Notice (
	"N_NO"	    NUMBER		                NOT NULL,
    "N_CATE"	VARCHAR2(100)               NOT NULL,
	"N_TITLE"	VARCHAR2(100)		        NOT NULL,
	"N_CONTENT"	VARCHAR2(1000)		        NOT NULL,
    "N_WRITER"  NUMBER                      NOT NULL,
	"N_CNT"	    NUMBER	    DEFAULT 0	    NOT NULL,
	"N_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"N_MOD"	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
    STATUS  CHAR(1)     DEFAULT 'N' CHECK(STATUS IN ('Y','N'))
);

COMMENT ON COLUMN Notice."N_CATE" IS '공지사항/FAQ';

ALTER TABLE Notice ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"N_NO"
);

DROP SEQUENCE SEQ_Notice_NO;
CREATE SEQUENCE SEQ_Notice_NO NOCACHE NOCYCLE;
INSERT INTO NOTICE (N_NO, N_CATE ,N_TITLE ,N_CONTENT ,N_WRITER ) VALUES ( SEQ_NOTICE_NO.NEXTVAL ,'공지사항', '추석인사' , '추석인사드립니다' , 1);
COMMIT;

SELECT * FROM Notice;

SELECT * FROM ( SELECT ROWNUM RNUM , RM.* FROM ( SELECT N.N_NO, N.N_CATE , N.N_TITLE , N.N_CONTENT , N.N_CNT , N.N_DATE FROM Notice N  WHERE N.N_WRITER = 1 AND N.STATUS = 'N' ORDER BY N.N_NO DESC ) RM ) WHERE RNUM BETWEEN 1 AND 152;
