--------------------------------
-- NOTICE
--------------------------------
DROP TABLE Notice CASCADE CONSTRAINTS;

CREATE TABLE Notice (
	"N_NO"	    NUMBER		                NOT NULL,
    "N_CATE"	VARCHAR2(100)               NOT NULL,
	"N_TITLE"	VARCHAR2(100)		        NOT NULL,
	"N_CONTENT"	VARCHAR2(1000)		        NOT NULL,
    "N_WRITER"  NUMBER                      NOT NULL,
	"N_CNT"	    NUMBER	    DEFAULT 0	    NOT NULL,
	"N_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"N_MOD"	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
    STATUS  CHAR(1)     DEFAULT 'N' CHECK(STATUS IN ('Y','N'))
);

COMMENT ON COLUMN Notice."N_CATE" IS '공지사항/FAQ';

ALTER TABLE Notice ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"N_NO"
);

DROP SEQUENCE SEQ_Notice_NO;
CREATE SEQUENCE SEQ_Notice_NO NOCACHE NOCYCLE;

INSERT INTO NOTICE (N_NO, N_CATE ,N_TITLE ,N_CONTENT ,N_WRITER ) VALUES ( SEQ_NOTICE_NO.NEXTVAL ,'공지사항', '설날인사' , '설날인사드립니다' , 1);
INSERT INTO NOTICE (N_NO, N_CATE ,N_TITLE ,N_CONTENT ,N_WRITER ) VALUES ( SEQ_NOTICE_NO.NEXTVAL ,'공지사항', '1분기 정기점검' , '오전 9시부로 1분기 정기점검 시작할 예정입니다.' , 1);
INSERT INTO NOTICE (N_NO, N_CATE ,N_TITLE ,N_CONTENT ,N_WRITER ) VALUES ( SEQ_NOTICE_NO.NEXTVAL ,'공지사항', '서비스 오류 안내' , '서비스가 일시적으로 중단되는 현상이 나타나고 있습니다. 서비스 이용에불편을 드려 사과드립니다.' , 1);
INSERT INTO NOTICE (N_NO, N_CATE ,N_TITLE ,N_CONTENT ,N_WRITER ) VALUES ( SEQ_NOTICE_NO.NEXTVAL ,'공지사항', '서비스 오픈안내' , '새로운 서비스 오픈 공지 드립니다.' , 1);
INSERT INTO NOTICE (N_NO, N_CATE ,N_TITLE ,N_CONTENT ,N_WRITER ) VALUES ( SEQ_NOTICE_NO.NEXTVAL ,'공지사항', '2분기 정기점검' , '오전 9시부로 2분기 정기점검 시작할 예정입니다.' , 1);
INSERT INTO NOTICE (N_NO, N_CATE ,N_TITLE ,N_CONTENT ,N_WRITER ) VALUES ( SEQ_NOTICE_NO.NEXTVAL ,'공지사항', '서비스 중단 안내' , '서비스 종료 안내 드립니다' , 1);
INSERT INTO NOTICE (N_NO, N_CATE ,N_TITLE ,N_CONTENT ,N_WRITER ) VALUES ( SEQ_NOTICE_NO.NEXTVAL ,'공지사항', '3분기 정기점검' , '오전 9시부로 3분기 정기점검 시작할 예정입니다.' , 1);
INSERT INTO NOTICE (N_NO, N_CATE ,N_TITLE ,N_CONTENT ,N_WRITER ) VALUES ( SEQ_NOTICE_NO.NEXTVAL ,'공지사항', '추석인사' , '추석인사드립니다' , 1);
INSERT INTO NOTICE (N_NO, N_CATE ,N_TITLE ,N_CONTENT ,N_WRITER ) VALUES ( SEQ_NOTICE_NO.NEXTVAL ,'공지사항', '4분기 정기점검' , '오전 9시부로 4분기 정기점검 시작할 예정입니다.' , 1);

COMMIT;

SELECT * FROM Notice;
--------------------------------
-- FAQ
--------------------------------
DROP TABLE FAQ CASCADE CONSTRAINTS;

CREATE TABLE FAQ (
	"FAQ_NO"	    NUMBER		                NOT NULL,
    "FAQ_CATE"	    VARCHAR2(100)               NOT NULL,
	"FAQ_TITLE"	    VARCHAR2(100)		        NOT NULL,
	"FAQ_CONTENT"	VARCHAR2(1000)		        NOT NULL,
    "FAQ_WRITER"    NUMBER                      NOT NULL,
	"FAQ_DATE"	    TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
     STATUS         CHAR(1)     DEFAULT 'N' CHECK(STATUS IN ('Y','N'))
);

DROP SEQUENCE SEQ_FAQ_NO;
CREATE SEQUENCE SEQ_FAQ_NO NOCACHE NOCYCLE;

COMMENT ON COLUMN FAQ."FAQ_CATE" IS '공지사항/FAQ';

ALTER TABLE FAQ ADD CONSTRAINT "PK_FAQ" PRIMARY KEY (
	"FAQ_NO"
);

INSERT INTO FAQ (FAQ_NO, FAQ_CATE , FAQ_TITLE , FAQ_CONTENT , FAQ_WRITER ) VALUES ( SEQ_FAQ_NO.NEXTVAL ,'기부', '기부하는법' , '기부신청은 홈페이지에서 확인하실수 있습니다' , 1);
COMMIT;

SELECT * FROM FAQ;
--------------------------------
-- FAQ_CATEGORY
--------------------------------
DROP TABLE FAQ_CATEGORY CASCADE CONSTRAINTS;
CREATE TABLE FAQ_CATEGORY(
    CATEGORY_NO     NUMBER           PRIMARY KEY,
    CATEGORY_NAME   VARCHAR2(30)     NOT NULL
);

INSERT INTO FAQ_CATEGORY(CATEGORY_NO , CATEGORY_NAME) VALUES(10, '기부');
INSERT INTO FAQ_CATEGORY(CATEGORY_NO , CATEGORY_NAME) VALUES(20, '펀딩');
INSERT INTO FAQ_CATEGORY(CATEGORY_NO , CATEGORY_NAME) VALUES(30, '캠페인');
INSERT INTO FAQ_CATEGORY(CATEGORY_NO , CATEGORY_NAME) VALUES(40, '기타');
COMMIT;

SELECT * FROM FAQ_CATEGORY;

